<?
$arUrlRewrite = array(
	array(
		"CONDITION" => "#^/group/([0-9]+)/contest/([0-9]+)/?#",
		"RULE" => "GROUP_ID=\$1&POST_ID=\$2",
		"ID" => "",
		"PATH" => "/group/contest/detail.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/events/([0-9]+)/?#",
		"RULE" => "GROUP_ID=\$1&POST_ID=\$2",
		"ID" => "",
		"PATH" => "/group/events/detail.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/post/([0-9]+)/?.*#",
		"RULE" => "GROUP_ID=\$1&POST_ID=\$2",
		"ID" => "",
		"PATH" => "/group/lenta/detail.php",
	),
	array(
		"CONDITION" => "#^/user/([0-9]+)/contest/([0-9]+)/?#",
		"RULE" => "user=\$1&POST_ID=\$2",
		"ID" => "",
		"PATH" => "/user/contest/detail.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/photo/([0-9]+)/?#",
		"RULE" => "GROUP_ID=\$1&POST_ID=\$2",
		"ID" => "",
		"PATH" => "/group/photo/detail.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/video/([0-9]+)/?#",
		"RULE" => "GROUP_ID=\$1&POST_ID=\$2",
		"ID" => "",
		"PATH" => "/group/video/detail.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/concept.ural2015#",
		"RULE" => "GROUP_ID=\$1",
		"ID" => "",
		"PATH" => "/group/concept.ural2015/index.php",
	),
	array(
		"CONDITION" => "#^/user/([0-9]+)/video/([0-9]+)/?#",
		"RULE" => "user=\$1&POST_ID=\$2",
		"ID" => "",
		"PATH" => "/user/video/detail.php",
	),
	array(
		"CONDITION" => "#^/user/([0-9]+)/photo/([0-9]+)/?#",
		"RULE" => "user=\$1&POST_ID=\$2",
		"ID" => "",
		"PATH" => "/user/photo/detail.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/u_concept/?#",
		"RULE" => "GROUP_ID=\$1",
		"ID" => "",
		"PATH" => "/group/u_concept/index.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/u_creative/?#",
		"RULE" => "GROUP_ID=\$1",
		"ID" => "",
		"PATH" => "/group/u_creative/index.php",
	),
	array(
		"CONDITION" => "#^/user/groups/all-groups/?#",
		"RULE" => "filter=all-groups",
		"ID" => "",
		"PATH" => "/user/groups/index.php",
	),
	array(
		"CONDITION" => "#^/communication/([0-9]+)/?#",
		"RULE" => "friend_in=\$1",
		"ID" => "",
		"PATH" => "/communication/index.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/contest/?#",
		"RULE" => "GROUP_ID=\$1",
		"ID" => "",
		"PATH" => "/group/contest/index.php",
	),
	array(
		"CONDITION" => "#^/user/([0-9]+)/contest/?#",
		"RULE" => "user=\$1",
		"ID" => "",
		"PATH" => "/user/contest/index.php",
	),
	array(
		"CONDITION" => "#^/user/([0-9]+)/profile/?#",
		"RULE" => "user=\$1",
		"ID" => "",
		"PATH" => "/user/profile/index.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/explore/#",
		"RULE" => "GROUP_ID=\$1",
		"ID" => "",
		"PATH" => "/group/explore/index.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/events/?#",
		"RULE" => "GROUP_ID=\$1",
		"ID" => "",
		"PATH" => "/group/events/index.php",
	),
	array(
		"CONDITION" => "#^/user/groups/my-groups/?#",
		"RULE" => "filter=my-groups",
		"ID" => "",
		"PATH" => "/user/groups/index.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/video/?#",
		"RULE" => "GROUP_ID=\$1",
		"ID" => "",
		"PATH" => "/group/video/index.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/photo/?#",
		"RULE" => "GROUP_ID=\$1",
		"ID" => "",
		"PATH" => "/group/photo/index.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/about/?#",
		"RULE" => "GROUP_ID=\$1&about=1",
		"ID" => "",
		"PATH" => "/group/index.php",
	),
	array(
		"CONDITION" => "#^/user/([0-9]+)/photo/?#",
		"RULE" => "user=\$1",
		"ID" => "",
		"PATH" => "/user/photo/index.php",
	),
	array(
		"CONDITION" => "#^/user/([0-9]+)/video/?#",
		"RULE" => "user=\$1",
		"ID" => "",
		"PATH" => "/user/video/index.php",
	),
	array(
		"CONDITION" => "#^/user/calendar/prev/?#",
		"RULE" => "filter=prev",
		"ID" => "",
		"PATH" => "/user/calendar/index.php",
	),
	array(
		"CONDITION" => "#^/user/calendar/next/?#",
		"RULE" => "filter=next",
		"ID" => "",
		"PATH" => "/user/calendar/index.php",
	),
	array(
		"CONDITION" => "#^/user/news/friends/?#",
		"RULE" => "filter=friends",
		"ID" => "",
		"PATH" => "/user/news/index.php",
	),
	array(
		"CONDITION" => "#^/user/news/groups/?#",
		"RULE" => "filter=groups",
		"ID" => "",
		"PATH" => "/user/news/index.php",
	),
	array(
		"CONDITION" => "#^/group/([0-9]+)/?#",
		"RULE" => "GROUP_ID=\$1",
		"ID" => "",
		"PATH" => "/group/index.php",
	),
	array(
		"CONDITION" => "#^/QR/([0-9]+)/#",
		"RULE" => "CODE=\$1",
		"ID" => "",
		"PATH" => "/QR/index.php",
	),
	array(
		"CONDITION" => "#^/contest/?#",
		"RULE" => "GROUP_ID=-1",
		"ID" => "",
		"PATH" => "/group/contest/index.php",
	),
);

?>
